name: RRRRHS
email: rrrrhs@gmail.com

navbar:
  title: RRRRHS
  logo: assets/images/RRRR_logo.png

splash:
  title: Raritan River Railroad Historical Society
  background: assets/images/RRRR-2-8-2-No.-12-South-Amboy-NJ-Header.jpg
  logo: assets/images/RRRR_logo.png
